In [10]:
#Numpy (numerical python)

#hızlı, sabit tipte veri tutarak
#yüksek(vektörel) seviyede işlem, az çaba çok iş

import numpy as np #çağırmada kısa yol oluşturma

x = np.array([11, 22, 33, 44])
y = np.array([22, 33, 44, 55])

x*y

array([ 242,  726, 1452, 2420])

In [6]:
#for ile

x = [11, 22, 33, 44]
y = [22, 33, 44, 55]

xy = []
for i in range(0, len(x)):
    xy.append(x[i]*y[i])
    
print(xy)

#döngü yok, append metodu yok, boş liste olouşturup eleman yönlendirme yok

[242, 726, 1452, 2420]


In [23]:
#array oluşturma

np.array([11, 22, 33, 44, 55])
type(np.array([11, 22, 33, 44, 55])) #numpy array'i oldu
                                     #herhangi bir yere atanmadığım için değişken kısmı boş

numpy.ndarray

In [17]:
type(np.array)
#python dilinde yerleşik bir fonk veya metot olduğunu gösterdi

builtin_function_or_method

In [18]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.random.randint(4, 22, size=8) 
#random modülünden randint metodu(alt,üst limit,tane)

array([10, 20, 18,  7, 10,  8,  6, 11])

In [20]:
np.random.normal(4, 2, (2, 2))
#istatiksel dağılıma göre(ort,stdev,sxs(boyut))


array([[6.16397935, 5.15946934],
       [1.53526407, 3.57514523]])

In [22]:
x = np.random.randint(22, size=4) #başlangıç belirtilmediğinde '0'
print(x.ndim) #boyut(1d)
print(x.shape) #boyut bilgileri
print(x.size) #toplam eleman
print(x.dtype) #tip bilgisi

1
(4,)
4
int32


In [28]:
#yeniden şekillendirme

print(np.random.randint(3, 9, (1,3)))
p = np.random.randint(3, 9, (1,3)).reshape(3,1) #eleman sayıları önemli
p.reshape(3, 1)

[[7 3 6]]


array([[3],
       [7],
       [4]])

In [56]:
#index seçimi

x = np.random.randint(22, size=4)
print([x])

[array([20, 13,  0,  5])]


In [57]:
x[2] = 777
print(x[2])

print([x])

print(x[0:2]) #dilimleme

777
[array([ 20,  13, 777,   5])]
[20 13]


In [66]:
y = np.random.randint(66, size=(5,11))
print(y)

[[33 36 64 45  4  7 31 44 49 29 61]
 [ 3 34 16 33  6  2 60 34 19 40  6]
 [52 44  8 63 60 21 64 20 15 43 10]
 [62 52  6 42 53 44 61 49 25  3 58]
 [ 2 14 44 28  0 64 50 13 53 48 12]]


In [67]:
y[2,2] #index ile değer çağırma
print(y[2,2])

8


In [76]:
y[2,2] = 777
print(y)

#float değer, uyarı alır veya int döndürür, hız için tipler eş olmalı

[[ 33  36  64  45   4   7  31  44  49  29  61]
 [  3  34  16  33   6   2  60  34  19  40   6]
 [ 52  44 777  63  60  21  64  20  15  43  10]
 [ 62  52   6  42  53  44  61  49  25   3  58]
 [  2  14  44  28   0  64  50  13  53  48  12]]


In [77]:
y[:, 0] #bütün satır, index 0

array([33,  3, 52, 62,  2])

In [78]:
y[0, :] #index 0, bütün sütun

array([33, 36, 64, 45,  4,  7, 31, 44, 49, 29, 61])

In [82]:
y[0:5,0:11] #dahillik

array([[ 33,  36,  64,  45,   4,   7,  31,  44,  49,  29,  61],
       [  3,  34,  16,  33,   6,   2,  60,  34,  19,  40,   6],
       [ 52,  44, 777,  63,  60,  21,  64,  20,  15,  43,  10],
       [ 62,  52,   6,  42,  53,  44,  61,  49,  25,   3,  58],
       [  2,  14,  44,  28,   0,  64,  50,  13,  53,  48,  12]])

In [92]:
#fancy index

t = np.arange(0,50, 5) #belirli bir adım boyunca array oluşturma
print(t)

hold = [3,6,9] #birden fazla index bilgisi girme

t[hold] #numpy array'ine liste yerleştirme

[ 0  5 10 15 20 25 30 35 40 45]


array([15, 30, 45])

In [4]:
import numpy as np

#Koşullu işlemler

h = np.array([23, 34, 45, 56])

#for ile

hp = []
for i in h:
    if i < 45:
        hp.append(i)

print(hp)

[23, 34]


In [6]:
#numpy ile
 #1. index çağırma,2. dilimleme,3. fancy seçim

print(h < 45) #istenen komut
h[h<45]

[ True  True False False]


array([23, 34])

In [10]:
#Matematiksel İşlemler

b = np.array([3, 6, 9])

b**2

array([ 9, 36, 81], dtype=int32)

In [13]:
print(np.subtract(b,2))
print(np.add(b,3))
print(np.mean(b))
print(np.min(b))
print(np.max(b))
print(np.var(b))
print(np.sum(b))

[1 4 7]
[ 6  9 12]
6.0
3
9
6.0
18


In [20]:
#denklem çözme

#5*x0 + x1 = 10
#x0 + 3*x1 = 10

#değişkenler=x0,x1 değerleri x'e ata
#sonuçlar=y1,y2 değerleri y'ye ata

x = np.array([[5,1], [1,3]])
y = np.array([10,10])

np.linalg.solve(x,y)

array([1.42857143, 2.85714286])